### ISSUE TITLE
ERROR in ./src/services/local-storage.service.js

### ISSUE THREAD

**Issue by vishwamartur** [vishwamartur/NEwitemtest#1]
Compiled with problems:
×
ERROR in ./src/services/local-storage.service.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\vmarturx\Videos\int\client\src\services\local-storage.service.js: Identifier 'localStorageService' has already been declared. (5:6)

  3 |
  4 | // Define the local storage service
> 5 | const localStorageService = {
    |       ^
  6 |     // Get the access token from the local storage
  7 |     getAccessToken() {
  8 |       return localStorage.getItem('accessToken');
    at constructor (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:356:19)
    at FlowParserMixin.raise (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:3223:19)
    at FlowScopeHandler.checkRedeclarationInScope (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:1496:19)
    at FlowScopeHandler.declareName (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:1467:12)
    at FlowScopeHandler.declareName (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:1563:11)
    at FlowParserMixin.declareNameFromIdentifier (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:7484:16)
    at FlowParserMixin.checkIdentifier (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:7480:12)
    at FlowParserMixin.checkLVal (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:7419:12)
    at FlowParserMixin.parseVarId (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:13280:10)
    at FlowParserMixin.parseVarId (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:5676:11)
    at FlowParserMixin.parseVar (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:13258:12)
    at FlowParserMixin.parseVarStatement (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:13100:10)
    at FlowParserMixin.parseStatementContent (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:12683:23)
    at FlowParserMixin.parseStatementLike (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:12588:17)
    at FlowParserMixin.parseStatementLike (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:5088:24)
    at FlowParserMixin.parseModuleItem (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:12565:17)
    at FlowParserMixin.parseBlockOrModuleBlockBody (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:13189:36)
    at FlowParserMixin.parseBlockBody (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:13182:10)
    at FlowParserMixin.parseProgram (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:12464:10)
    at FlowParserMixin.parseTopLevel (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:12454:25)
    at FlowParserMixin.parseTopLevel (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:5893:28)
    at FlowParserMixin.parse (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:14376:10)
    at parse (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\parser\lib\index.js:14417:38)
    at parser (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\core\lib\parser\index.js:41:34)
    at parser.next (<anonymous>)
    at normalizeFile (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\core\lib\transformation\normalize-file.js:64:37)
    at normalizeFile.next (<anonymous>)
    at run (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\core\lib\transformation\index.js:21:50)
    at run.next (<anonymous>)
    at transform (C:\Users\vmarturx\Videos\int\client\node_modules\@babel\core\lib\transform.js:22:33)
    at transform.next (<anonymous>)
    at step (C:\Users\vmarturx\Videos\int\client\node_modules\gensync\index.js:261:32)
    at C:\Users\vmarturx\Videos\int\client\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (C:\Users\vmarturx\Videos\int\client\node_modules\gensync\index.js:223:11)
    at C:\Users\vmarturx\Videos\int\client\node_modules\gensync\index.js:189:28
    at C:\Users\vmarturx\Videos\int\client\node_modules\@babel\core\lib\gensync-utils\async.js:67:7
    at C:\Users\vmarturx\Videos\int\client\node_modules\gensync\index.js:113:33
    at step (C:\Users\vmarturx\Videos\int\client\node_modules\gensync\index.js:287:14)
    at C:\Users\vmarturx\Videos\int\client\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (C:\Users\vmarturx\Videos\int\client\node_modules\gensync\index.js:223:11)
ERROR
[eslint] 
src\services\local-storage.service.js
  Line 5:6:  Parsing error: Identifier 'localStorageService' has already been declared. (5:6)

**Comment by vishwamartur** [comment]
Commented out // the import file line issue resolved
